name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git
        run: |
          git config user.name jeremybosma
          git config user.email jectaunscripted@gmail.com
      - name: Authenticate with Git
        env:
          GITHUB_TOKEN: ${{ secrets.GHP_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      - run: git checkout -b origin/main
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - name: Set and push version from release tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          npm version $VERSION --no-git-tag-version
          git push -u origin main
    #   - run: npm ci
    #   - run: npm publish --provenance --access public
